#!/usr/bin/env python3

import time,os,openpyxl
from selenium import webdriver
import pandas as pd
from openpyxl import Workbook

def load_handling(method): #Esto me permite basicamente agarar cualquier funcion y agregarle que lo reintente cada x tiempo
    while True:
        timer=0
        try:
            method
            break
        except:
            time.sleep(5)
            timer+=1
            if timer > 20:
                    print('El SADE esta trabadisimo (o algo terrible paso) al tratar de clickear el boton '+method+'. Cuando se destrabe, presiona ENTER')
                    input()
            continue
def xpath_click(path):
        timer=0
        while True:
                try:
                        driver.find_element_by_xpath(path).click()
                        time.sleep(1)
                        break
                
                except:
                        time.sleep(5)
                        timer+=1
                        if timer > 20:
                                print('El SADE esta trabadisimo (o algo terrible paso) al tratar de clickear el boton '+path+'. Cuando se destrabe, presiona ENTER')
                                input()
                        continue
def xpath_send(path,Keys):
        timer=0
        while True:
                try:                
                        driver.find_element_by_xpath(path).clear()
                        driver.find_element_by_xpath(path).send_keys(Keys)
                        time.sleep(1)
                        break                
                except:
                        time.sleep(5)
                        timer+=1
                        if timer > 20:
                                print('El SADE esta trabadisimo (o algo terrible paso). Al tratar de mandar el siguiente mensaje '+Keys+' Cuando se destrabe, presiona ENTER')
                                input()
                        continue       
def barra():
    print('~'*80)
print('''Bienvenido al modulo de carga de SADE.
A diferencia del modulo PATA, este tiene bastante poca interaccion, ya que debido a la naturaleza de las paginas webs, no hay mucho para "introducir manualmente"
Lo unico que puede llegar a pasar, es que el BENDITO SADE se trabe, como siempre, entonces el programa al notar que esta todo trabado se pausara y te pedira que apretes "ENTER"(o cualquier tecla)
para seguir con la subida. En cualquier momento podes cerrar esto, lo que si te quedara abierto la actuacion.
Todos los numeros de SADE, junto a su cooperacion se exportaran a un excel que estara en la misma carpeta que este archivo.''')
Disco=input('Que letra es el disco compartido?   ').upper()
#----------------------------------------------------------------------------------------------------------------
#Aca abre el explorador
try:
        driver = webdriver.Chrome()
        driver.get('https://eu-pr.apps.buenosaires.gob.ar/eu-web/')
        driver.maximize_window()
        driver.find_element_by_id("user-input").send_keys('20261657962')
except:
        print('Error al abrir la pagina del SADE')  

#----------------------------------------------------------------------------------------------------------------
#Esto es para bypasear el Captcha
print('Cuando pases el Captcha, apreta enter(Onda, soy un robot. Esos Captcha dan miedo)')
input()
#----------------------------------------------------------------------------------------------------------------
#lLOGEO AL GEDO                 
driver.find_element_by_id('pass-input').send_keys('Nubia007')
driver.find_element_by_id("ddjj-login-form").submit()
window_before = driver.window_handles[0]
driver.execute_script("window.open('https://eut-pr.apps.buenosaires.gob.ar/gedo-web/', 'new window')")
window_after = driver.window_handles[1]
driver.switch_to.window(window_after)
time.sleep(5)
xpath_send(('//*[@id="username"]'),'20261657962')
xpath_send(('//*[@id="password"]'),'Nubia007')
driver.find_element_by_id('password').submit()
GEDOS_HECHOS=[]
COOP_HECHAS=[]
IFs=[]
#----------------------------------------------------------------------------------------------------------------

#apartir de aca, va la subida de archivos
carpeta_encontrada=False
while True:
        if carpeta_encontrada==True:
                break        
        carpeta=input('Introduzca nombre de la carpeta   ').upper()
        if carpeta=='':
                carpeta_root=r'J:\ACTAS ESCANEADAS RAKY\AÑO 2019\AGOSTO\1-8-19'
        path = Disco+':\\ACTAS ESCANEADAS RAKY\\'
        for root, dirs, files in os.walk(path):
                for folders in dirs:
                        if folders == carpeta:
                                carpeta_root=os.path.join(root, folders)
                                print('Carpeta encontrada!')
                                carpeta_encontrada=True
                                break
for root, dirs, files in os.walk(carpeta_root):
        for filename in files:    
                if filename.endswith('.xlsx'):
                        filepath_name=os.path.join(root, filename)
                        wb = openpyxl.load_workbook(filepath_name)
                        try:
                                ws=wb['SADE']
                        except:
                                ws=wb['Sheet1']
                        for rowNum in range(1, ws.max_row+1): 
                                if not ws.cell(row=rowNum, column=1).value==None:
                                        if ws.cell(row=rowNum, column=1).value.endswith('-19')==False:
                                                ws.cell(row=rowNum, column=1).value=ws.cell(row=rowNum, column=1).value+'-19'
                                                wb.save(filepath_name)
                                                break
                elif filename.startswith('RECIBO'):
                        filepath_name=os.path.join(root, filename)
                        while True:
                                try:
                                        Ini_Doc=driver.find_element_by_class_name('z-toolbarbutton') #boton de inciar documento
                                        Ini_Doc.click()
                                        break
                                except:
                                        time.sleep(5)
                        while True:
                                timer=0
                                try:
                                        driver.find_element_by_css_selector('input.z-bandbox-inp[autocomplete="off"]').send_keys('IFGRA')#introducir IFGRA. BUSCAR MEJOR MANERA DE DEFINIR ESTE ELEMENTO
                                        break
                                except:
                                        time.sleep(5)
                                        timer+=1
                                        if timer > 20:
                                                print('El SADE esta trabadisimo (o algo terrible paso). Cuando se destrabe, presiona ENTER')
                                                input()
                                        continue
                        while True:
                                        try:
                                                load_handling(driver.find_element_by_css_selector('.z-toolbarbutton[title="Continuar con la tarea de producción del documento."]').click())#Clickear boton de iniciar yo mismo
                                                break
                                        except:
                                                continue
                        coop=filename.strip('.pdf')#NUMERO DE COOPERACION <input id="z_58v_th" style="width:350px;" class="z-textbox" value="" type="text" maxlength="250">
                        time.sleep(5)
                        while True:
                                timer=0
                                try:
                                        driver.find_element_by_css_selector('input.z-textbox[maxlength="250"]').send_keys(coop)#poner el nombre de la cooperacion
                                        break
                                except:
                                        time.sleep(5)
                                        timer+=1
                                        if timer > 20:
                                                print('El SADE esta trabadisimo (o algo terrible paso). Cuando se destrabe, presiona ENTER')
                                                input()
                                        continue          
                        path=filepath_name                                
                        time.sleep(2)
                        load_handling(driver.find_element_by_css_selector('input[name="file"][type="file"][hidefocus="true"]').send_keys(path))#lugar donde esta el archivo
                        load_handling(driver.find_element_by_xpath('//img[@src="/gedo-web/imagenes/FirmarYoMismoElDocumento.png"]').click())
                        xpath_click('//img[@src="./imagenes/FirmarConCertificado.png"]')
                        time.sleep(10)
                        while True:
                                timer=0
                                try:
                                        Respuesta_GEDO= driver.find_element_by_css_selector('*[style="text-align:left;width:100%"][cellpadding="0"]')#lugar donde esta el archivo
                                        #texto sade
                                        Respuesta_GEDO=Respuesta_GEDO.text
                                        Respuesta_GEDO=Respuesta_GEDO.split('IF')
                                        Respuesta_GEDO='IF'+Respuesta_GEDO[1]
                                        IF=Respuesta_GEDO.split('-')
                                        IF=IF[2]
                                        break
                                except:
                                        time.sleep(5)
                                        timer+=1
                                        if timer > 20:
                                                print('El SADE esta trabadisimo (o algo terrible paso). Cuando se destrabe, presiona ENTER')
                                                input()
                                        continue          
                        GEDOS_HECHOS.append(Respuesta_GEDO)
                        COOP_HECHAS.append(coop)
                        IFs.append(IF)
                        barra()
                        print('Se subio la Cooperacion '+coop+', con el codigo '+Respuesta_GEDO)
                        barra()
                        xpath_click('//img[@src="./imagenes/VolverAlBuzonTareas.png"]')
#-------------------------------------------------------------
#PASO LOS NUMEROS DE SADE AL EXCEL. FALTA TERMINAR LA PARTE DEL EXCEL

wb = Workbook()
ws = wb.active
ws.title = "SADE"
sheet=wb['SADE']
sheet['A1']='Cooperacion'
sheet['B1']='IF COMPLETO'
sheet['C1']='CODIGO IF para PASE'
sheet['D1']='EX' 
_=len(GEDOS_HECHOS)+2 
for rowNum in range(2,_):
        sheet.cell(row=rowNum, column=1).value = COOP_HECHAS[rowNum-2]
        sheet.cell(row=rowNum, column=2).value = GEDOS_HECHOS[rowNum-2]
        sheet.cell(row=rowNum, column=3).value = IFs[rowNum-2]
wb.save(carpeta_root+'\\NUMEROS_DE_SADE.xlsx')

#---------------------------
print('Las siguientes cooperaciones fueron cargadas con exito:')
barra()
for weas in COOP_HECHAS:
        print(weas)
barra()
input('Apretar enter para cerrar\n')
